steps:

    #
    # Building
    #
  
    - id: build-builder
      name: gcr.io/cloud-builders/docker
      dir: cloudbuild/
      args: [
                'build',
                '--rm=false',
                '-t','eu.gcr.io/$PROJECT_ID/pyslo-builder:latest',
                '--cache-from', 'eu.gcr.io/$PROJECT_ID/pyslo-builder:latest',
                '-f', './Dockerfile', '.'
        ]
    
    #
    # Testing
    #

    - id: test
      name: eu.gcr.io/$PROJECT_ID/pyslo-builder
      args: ['cloudbuild/scripts/test.sh']
      waitFor:
        - build-builder